services:
  mongo:
    image: mongo:7.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
    volumes:
      - mongo_data:/data/db
    networks:
      - backend


volumes:
  mongo_data:

networks:
  backend:
    driver: bridge